version: '3'
services:

  rabbitmq: # login guest:guest
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.localhost`)"
      - "traefik.http.routers.rabbitmq.entrypoints=web"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"

  backend:
    build: ./backend
    ports:
      - '3025:3025'
    environment:
      - RABBIT_HOSTNAME=rabbitmq
    volumes:
      - ./backend:/app
    depends_on:
      - rabbitmq
    command: bash -c "tsc && npm run watch"
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.localhost`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=3025"

  front:
    build: ./front
    ports:
      - '5055:5055' # see front/package.json 'preview'/'dev' --port value
    volumes:
      - ./front:/app
    command: bash -c "npm run build && npm run dev"
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`front.localhost`)"
      - "traefik.http.routers.front.entrypoints=web"

  # https://doc.traefik.io/traefik/getting-started/quick-start/
  reverse-proxy:    
    image: traefik:v3.0 # The official v3 Traefik docker image
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false" # ignore ie. promethues
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80" # to able serve traffic for exposed hosts, like front.localhost or traefik.localhost
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`traefik.localhost`)"
        - "traefik.http.routers.api.service=api@internal"
