version: '3'
services:

  rabbitmq: # login guest:guest
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'

  backend:
    build: ./backend
    ports:
      - '3025:3025'
    environment:
      - RABBIT_HOSTNAME=rabbitmq
    volumes:
      - ./backend:/app
    depends_on:
      - rabbitmq
    command: bash -c "tsc && npm run watch"
    restart: on-failure

  front:
    build: ./front
    ports:
      - '5055:5055' # see front/package.json 'preview' --port value
    volumes:
      - ./front:/app
    command: bash -c "npm run build && npm run preview"
    restart: on-failure