version: '3'
services:

  rabbitmq: # login guest:guest
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'

  backend:
    build: ./backend
    ports:
      - '3025:3025'
    environment:
      - RABBIT_HOSTNAME=rabbitmq
    volumes:
      - ./backend:/app
    depends_on:
      - rabbitmq
    command: bash -c "tsc && nodemon dist/server.js"
    restart: on-failure
